### ISSUE TITLE
Submission adapter copywriting and defaults

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#23]
1) Not sure how to change the copywriting for the submission adapter options. I'd like them to be as follows:

![screen shot 2016-04-26 at 11 49 32 pm](https://cloud.githubusercontent.com/assets/1328849/14844053/8d22fce2-0c09-11e6-82f1-87716007b13d.png)

2) Email should be the default selection here, I think. Otherwise, it's easy for admins to post opportunities while overlooking that there is no way for vendors to apply. If email's selected by default, the worst-case scenario is that someone gets a few emails by mistake. But that's easy to fix: they can manually enter in Screendoor or forward to the correct individual.

3) If the user selects "Neither", we should warn them of what they need to do. Something like:

![screen shot 2016-04-27 at 12 02 51 am](https://cloud.githubusercontent.com/assets/1328849/14844313/683a71c4-0c0b-11e6-82a0-3779a1bd4fc6.png)

**Comment by ajb** [comment]
"Neither Screendoor nor email" will not work as copy, because part of the customizability of this app is that users can create additional submission adapters.

I can take care of the rest of this.

**Comment by ajb** [comment]
This is done in the `polish` branch, but one more thing:

"Otherwise, vendors won't know how to contact you" is technically incorrect, since every opportunity has contact details that are different than the submission details. Additionally, some governments use systems like Dispatch to advertise notices to sole source, which wouldn't have submission details. This is an edge case... but maybe we want to make our warning a bit more specific?

**Comment by jrubenoff** [comment]
How about "none of the above"?

![screen shot 2016-04-27 at 12 08 25 pm](https://cloud.githubusercontent.com/assets/1328849/14864878/c4807afe-0c70-11e6-9694-d4618d441249.png)

I made the warning broader, to cover more use cases.

**Comment by ajb** [comment]
Changing to "None of the above". Looks great.
